#CI Nível 02 - Disparo de forma automática

#Nome que vai aparecer nas opções de pipe
name: 'Execução Agendada'

on:
  schedule:
   - cron: '10 20 * * *'
    
    #cron POSIX a b c d e 
    # a -> minuto
    # b -> hora
    # c -> dias do mês
    # d -> meses do ano 
    # e -> dias da semana

jobs:
  e2e-testes:
    runs-on: ['ubuntu-latest']
    steps:
      
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencies
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Testes E2E
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }} 
        with:
          name: tests_reports
          path: ./playwright-report 
