#CI Nível 04 - Disparo dentro do fluxo de CI de Desenvolvimento

name: 'Execução Integrada'

on:
  workflow_dispatch:


jobs:
  inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencies
        run: yarn
        
      - name: Lint / Prettier (Padronização de Código)
        run: yarn lint
        
  e2e-testes:
 
    runs-on: ['ubuntu-latest']

 
    steps:
      
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencies
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Testes E2E
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }} 
        with:
          name: tests_reports
          path: ./playwright-report 
